# Generated by Django 4.2.1 on 2023-05-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0002_weekday_alter_user_course_note'),
    ]

    operations = [
    ]
