# Generated by Django 4.2.1 on 2023-05-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0003_auto_20230523_1557'),
    ]

    operations = [
    ]
