# Generated by Django 4.2.1 on 2023-05-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_school', '0004_auto_20230523_1559'),
    ]

    operations = [
    ]
